### ISSUE TITLE
Etlua Syntax Highlighting for Vim

### ISSUE THREAD

**Issue by VaiN474** [leafo/etlua#3]
I've created etlua syntax highlighting for vim.

It's available for [etlua files](https://github.com/VaiN474/vim-etlua) (with HTML) and for [plain text files](https://github.com/VaiN474/vim-etlua-plain), in case you want to template other file types.

I had a partially working one for Sublime Text as well but haven't looked at it in a while. If anyone is interested in that let me know, and I'll see if I can dig it up.

**Comment by leafo** [comment]
We can add it to the readme if you want to make a pull requrest
